hide_download: true
hide_download_original: null
leftnav:
- identifier: 4b5760d2-5c5c-295d-cc96-3ea6691c3827
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 41de48fc-370a-b875-43f1-50364b3771d0
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 2731d273-06a6-74aa-8502-ee2adfb6aaaf
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 209f6e0c-04e0-2cf5-649a-1f72ea232d01
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 906956e5-4a15-8ec7-17c6-8c8641f10915
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 2fb9fff0-5f14-66d6-2a06-bbebc234d47a
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: 1e846f9f-eb56-5ace-98f1-7df4ff859b42
  name: Textbooks
  pageRef: /pages/textbooks
  weight: 70
- identifier: 631e0785-b31d-58bd-5e9f-f5de9a9820a8
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 80
